tasks:
  - name: install-aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: echo 'installing AWS CLI'
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $GITPOD_REPO_ROOT